name: Lint and Format Check


on:
  pull_request:
    branches:
      - main  # マージ先のブランチを指定
    types:
      - closed

jobs:
  lint_and_format:
    name: ESLintとPrettierの実行
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 必要な依存関係をインストール
        run: |
          cd sample_frontend_container/sample_remix_react
          npm install

      - name: ESLintを実行
        run: |
          cd sample_frontend_container/sample_remix_react
          npm run lint

      - name: Prettierのフォーマット確認
        run: |
          cd sample_frontend_container/sample_remix_react
          npm run format:check

      - name: TypeScript型チェックを実行
        run: |
          cd sample_frontend_container/sample_remix_react
          npm run typecheck