name: eslint, prettier

on:
  pull_request:
  # プルリクエストにプッシュするたびに実行したい場合はtypesをコメントにする
    # types: 
    #   - closed
    # プルリクエストがマージされるときにこのワークフローをトリガーします。
  workflow_dispatch:
    # 手動でこのワークフローをトリガーします。


jobs:
  eslint_and_prettier:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Add swap space
        run: |
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Set up frontend Container
        run: |
          docker-compose up -d frontend

      - name: Run eslint in frontend Container
        run: |
          CONTAINER_ID=$(docker ps -qf "name=sample_frontend_container")
          docker exec $CONTAINER_ID npm run format

      - name: Run prettier in frontend Container
        run: |
          CONTAINER_ID=$(docker ps -qf "name=sample_frontend_container")
          docker exec $CONTAINER_ID npm run lint
